run_tests:
	python3 -m unittest discover uwqsc_backtesting_framework/tests -p '*_test.py'
	coverage run --source=uwqsc_backtesting_framework/src -m unittest discover uwqsc_backtesting_framework/tests -p '*_test.py'
	coverage report -m